# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"\"\n\x12HelloRequestHieuNV\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x10HelloReplyHieuNV\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\x07Greeter\x12>\n\x08SayHello\x12\x19.greet.HelloRequestHieuNV\x1a\x17.greet.HelloReplyHieuNVb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUESTHIEUNV._serialized_start=22
  _HELLOREQUESTHIEUNV._serialized_end=56
  _HELLOREPLYHIEUNV._serialized_start=58
  _HELLOREPLYHIEUNV._serialized_end=93
  _GREETER._serialized_start=95
  _GREETER._serialized_end=168
# @@protoc_insertion_point(module_scope)
